# -*- coding: utf-8 -*-
"""pd-request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ni8Gj7wiY1TSDJD2Uo89U_LDMk6hk0Rn
"""
import numpy as np
import pandas as pd
import sqlite3

username = 'Rocknroll-nerd'
repo = 'Skolkovo-hack/'
token = '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'

link = '/content/drive/MyDrive/for_hack_2022/result/result_job_#jobId.csv'
cand_link = '/content/drive/MyDrive/for_hack_2022/data_candidates.csv'
def csvScoretoHTML(link = link, cand_link=cand_link, **args):
  columns = ['CandidateId', 'Score']
  h_cand = ['CandidateId', 
            'Position',
            'Sex', 
            'Citizenship', 
            'Age', 
            'Salary', 
            'Langs', 
            'DriverLicense', 
            'Subway',
            'Skills', 
            'Employment', 
            'Shedule', 
            'CandidateRegion', 
            'DateCreated', 'JobId', 'CandidateStatusId', 'Status']
  out = pd.read_csv(link, header=None, sep=";", names=columns)
  jobs = pd.read_csv(cand_link, header=None, sep=";", names=h_cand)
  jobs.drop(['Sex', 
            'Citizenship', 
            'Age', 
            'Salary', 
            'Langs', 
            'DriverLicense', 
            'Subway',
            'Skills', 
            'Employment', 
            'Shedule', 
            'CandidateRegion', 
            'DateCreated', 'JobId', 'CandidateStatusId', 'Status'], axis=1, inplace=True)
  df = pd.merge(out, jobs, on = 'CandidateId')
  #df.drop_duplicates(inplace=True)
  return jobs, df

#неужели там нет таких айдишников
data_ifempty = {'CandidateId': [i for i in range(123, 133)], 'Score':np.random.random(size=10)}
if csvScoretoHTML()[1].empty:
  pd.DataFrame(data_ifempty).to_html('pages/html_table.js')
else:  
  csvScoretoHTML()[1].to_html('pages/html_table.js')

